//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_redes_sociales_empresa
    {
        public int cms_redes_sociales_empresa_id { get; set; }
        public string url_facebook { get; set; }
        public string url_youtube { get; set; }
    }
}
