//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_seccion_contenido
    {
        public int cms_seccion_contenido_id { get; set; }
        public int cms_seccion_id { get; set; }
        public string html_control_id { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha_creado { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
    
        public virtual cms_seccion cms_seccion { get; set; }
    }
}
