//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_seccion_home_carrusel_noticias
    {
        public int cms_seccion_home_carrusel_noticias_id { get; set; }
        public string nombre_archivo { get; set; }
        public string url_redireccion { get; set; }
        public bool activo_inactivo { get; set; }
        public int orden { get; set; }
        public Nullable<bool> movil { get; set; }
    }
}
