//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_informacion_contacto_empresa
    {
        public int cms_informacion_contacto_empresa_id { get; set; }
        public string telefono_contacto { get; set; }
        public string direccion_fisica { get; set; }
    }
}
