//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_home_carrusel
    {
        public int cms_home_carrusel_id { get; set; }
        public string descripcion { get; set; }
        public string imagen_escritorio { get; set; }
        public string imagen_movil { get; set; }
        public string url_redireccion { get; set; }
        public int usuario_creo { get; set; }
        public System.DateTime fecha_creo { get; set; }
        public int orden { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public bool activo_inactivo { get; set; }
    }
}
