//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cultivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cultivos()
        {
            this.productos_cultivos = new HashSet<productos_cultivos>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string data_crudo { get; set; }
        public bool activo_inactivo { get; set; }
        public int usuario_bitacora { get; set; }
        public System.DateTime fecha_bitacora { get; set; }
        public string contexto_bitacora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_cultivos> productos_cultivos { get; set; }
    }
}
