//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfermedades
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string data_crudo { get; set; }
        public bool activo_inactivo { get; set; }
        public int usuario_bitacora { get; set; }
        public System.DateTime fecha_bitacora { get; set; }
        public string contexto_bitacora { get; set; }
    }
}
