//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_aplicacion
    {
        public int evento_aplicacion_id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int evento_aplicacion_tipo_id { get; set; }
    
        public virtual evento_aplicacion_tipo evento_aplicacion_tipo { get; set; }
    }
}
