//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class frasegu_modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frasegu_modulo()
        {
            this.frasegu_modulo_nivel = new HashSet<frasegu_modulo_nivel>();
        }
    
        public int frasegu_modulo_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public bool activo_inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frasegu_modulo_nivel> frasegu_modulo_nivel { get; set; }
    }
}
