//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class frasegu_modulo_nivel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frasegu_modulo_nivel()
        {
            this.frasegu_usuario_perfil = new HashSet<frasegu_usuario_perfil>();
        }
    
        public int frasegu_modulo_nivel_id { get; set; }
        public int nivel { get; set; }
        public string descripcion { get; set; }
        public int frasegu_modulo_id { get; set; }
    
        public virtual frasegu_modulo frasegu_modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frasegu_usuario_perfil> frasegu_usuario_perfil { get; set; }
    }
}
