//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class modutrack_ingreso_fallido_aplicacion
    {
        public int modutrack_ingreso_aplicacion_id { get; set; }
        public string correo_fallido { get; set; }
        public string pass_fallida { get; set; }
        public string sistema_ip { get; set; }
        public string sistema_operativo { get; set; }
        public string sistema_navegador { get; set; }
        public System.DateTime sistema_fecha { get; set; }
    }
}
