//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Composicion
    {
        public int id { get; set; }
        public int id_Producto { get; set; }
        public string ingrediente { get; set; }
        public string formula { get; set; }
        public Nullable<bool> tipo { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string porcentaje { get; set; }
        public bool usable { get; set; }
        public Nullable<bool> active_inactive { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
