//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Documentos
    {
        public int id { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<int> id_Tipo { get; set; }
        public string tipo_Documento { get; set; }
        public string documento { get; set; }
        public string ruta { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
