//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.P_Aplicacion = new HashSet<P_Aplicacion>();
            this.P_Composicion = new HashSet<P_Composicion>();
            this.P_Documentos = new HashSet<P_Documentos>();
            this.productos_cultivos = new HashSet<productos_cultivos>();
            this.productos_cultivos1 = new HashSet<productos_cultivos>();
            this.productos_enfermedades = new HashSet<productos_enfermedades>();
        }
    
        public int id { get; set; }
        public int id_tipo { get; set; }
        public string sku { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string presentacion { get; set; }
        public string contenido { get; set; }
        public string beneficios { get; set; }
        public string imagen { get; set; }
        public string pdf_nombre { get; set; }
        public Nullable<bool> status { get; set; }
        public string subnombre { get; set; }
        public string Cintillo { get; set; }
        public Nullable<bool> show_index { get; set; }
        public string pie { get; set; }
        public string imagen_logo { get; set; }
        public string imagen_logo_carpeta { get; set; }
        public string imagen_logo_blanco { get; set; }
        public Nullable<int> cms_tablas_composicion_id { get; set; }
        public double precio { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string imagen_tabla_aplicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Aplicacion> P_Aplicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Composicion> P_Composicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Documentos> P_Documentos { get; set; }
        public virtual P_Tipo P_Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_cultivos> productos_cultivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_cultivos> productos_cultivos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_enfermedades> productos_enfermedades { get; set; }
    }
}
