//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versa_Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_cultivos
    {
        public int id_producto { get; set; }
        public int id_cultivo { get; set; }
    
        public virtual cultivos cultivos { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
