//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.carzapc.apis.files.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApiFilesVersaV3Entities : DbContext
    {
        public ApiFilesVersaV3Entities()
            : base("name=ApiFilesVersaV3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int cms_borrarEstructuraTablaAplicacion(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_borrarEstructuraTablaAplicacion", idProductoParameter);
        }
    
        public virtual int cms_borrarImagenTablaAplicacion(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_borrarImagenTablaAplicacion", idProductoParameter);
        }
    
        public virtual int cms_cmsHomeCarruselNuevo(string descripcion, string imagen_escritorio, string imagen_movil, string url_redireccion, Nullable<int> usuario_creo, Nullable<int> orden)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var imagen_escritorioParameter = imagen_escritorio != null ?
                new ObjectParameter("imagen_escritorio", imagen_escritorio) :
                new ObjectParameter("imagen_escritorio", typeof(string));
    
            var imagen_movilParameter = imagen_movil != null ?
                new ObjectParameter("imagen_movil", imagen_movil) :
                new ObjectParameter("imagen_movil", typeof(string));
    
            var url_redireccionParameter = url_redireccion != null ?
                new ObjectParameter("url_redireccion", url_redireccion) :
                new ObjectParameter("url_redireccion", typeof(string));
    
            var usuario_creoParameter = usuario_creo.HasValue ?
                new ObjectParameter("usuario_creo", usuario_creo) :
                new ObjectParameter("usuario_creo", typeof(int));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_cmsHomeCarruselNuevo", descripcionParameter, imagen_escritorioParameter, imagen_movilParameter, url_redireccionParameter, usuario_creoParameter, ordenParameter);
        }
    
        public virtual int cms_documentoEsrActualizar(string nombre_archivo)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_documentoEsrActualizar", nombre_archivoParameter);
        }
    
        public virtual ObjectResult<string> cms_documentoEsrObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("cms_documentoEsrObtener");
        }
    
        public virtual int cms_informacionContactoEmpresaActualizar(string telefono_contacto, string direccion_fisica)
        {
            var telefono_contactoParameter = telefono_contacto != null ?
                new ObjectParameter("telefono_contacto", telefono_contacto) :
                new ObjectParameter("telefono_contacto", typeof(string));
    
            var direccion_fisicaParameter = direccion_fisica != null ?
                new ObjectParameter("direccion_fisica", direccion_fisica) :
                new ObjectParameter("direccion_fisica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_informacionContactoEmpresaActualizar", telefono_contactoParameter, direccion_fisicaParameter);
        }
    
        public virtual ObjectResult<cms_informacionContactoEmpresaObtener_Result> cms_informacionContactoEmpresaObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_informacionContactoEmpresaObtener_Result>("cms_informacionContactoEmpresaObtener");
        }
    
        public virtual int cms_logotipoEmpresaActualizar(string nombre_imagen)
        {
            var nombre_imagenParameter = nombre_imagen != null ?
                new ObjectParameter("nombre_imagen", nombre_imagen) :
                new ObjectParameter("nombre_imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_logotipoEmpresaActualizar", nombre_imagenParameter);
        }
    
        public virtual ObjectResult<string> cms_logotipoEmpresaObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("cms_logotipoEmpresaObtener");
        }
    
        public virtual int cms_modufilesArchivoNuevo(string archivo_hash)
        {
            var archivo_hashParameter = archivo_hash != null ?
                new ObjectParameter("archivo_hash", archivo_hash) :
                new ObjectParameter("archivo_hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_modufilesArchivoNuevo", archivo_hashParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> cms_modufilesArchivoNuevoId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("cms_modufilesArchivoNuevoId");
        }
    
        public virtual ObjectResult<string> cms_obtImagenTabla(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("cms_obtImagenTabla", idParameter);
        }
    
        public virtual ObjectResult<cms_obtNombreUsuario_Result> cms_obtNombreUsuario(Nullable<int> usuario_id)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_obtNombreUsuario_Result>("cms_obtNombreUsuario", usuario_idParameter);
        }
    
        public virtual int cms_productoActualizarTablaAplicacion(string imagen_tabla_aplicacion, Nullable<int> id)
        {
            var imagen_tabla_aplicacionParameter = imagen_tabla_aplicacion != null ?
                new ObjectParameter("imagen_tabla_aplicacion", imagen_tabla_aplicacion) :
                new ObjectParameter("imagen_tabla_aplicacion", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_productoActualizarTablaAplicacion", imagen_tabla_aplicacionParameter, idParameter);
        }
    
        public virtual int cms_pSkuNuevo(string sku)
        {
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_pSkuNuevo", skuParameter);
        }
    
        public virtual ObjectResult<cms_pSkuObtener_Result> cms_pSkuObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_pSkuObtener_Result>("cms_pSkuObtener");
        }
    
        public virtual int cms_pTipoActualizar(Nullable<int> id, string nombre, string imagen, string alias, string classname_img_mobile)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var aliasParameter = alias != null ?
                new ObjectParameter("alias", alias) :
                new ObjectParameter("alias", typeof(string));
    
            var classname_img_mobileParameter = classname_img_mobile != null ?
                new ObjectParameter("classname_img_mobile", classname_img_mobile) :
                new ObjectParameter("classname_img_mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_pTipoActualizar", idParameter, nombreParameter, imagenParameter, aliasParameter, classname_img_mobileParameter);
        }
    
        public virtual int cms_pTipoEliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_pTipoEliminar", idParameter);
        }
    
        public virtual int cms_pTipoNuevo(string nombre, string imagen, string alias, string classname_img_mobile)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var aliasParameter = alias != null ?
                new ObjectParameter("alias", alias) :
                new ObjectParameter("alias", typeof(string));
    
            var classname_img_mobileParameter = classname_img_mobile != null ?
                new ObjectParameter("classname_img_mobile", classname_img_mobile) :
                new ObjectParameter("classname_img_mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_pTipoNuevo", nombreParameter, imagenParameter, aliasParameter, classname_img_mobileParameter);
        }
    
        public virtual ObjectResult<cms_pTipoObtenerTodos_Result> cms_pTipoObtenerTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_pTipoObtenerTodos_Result>("cms_pTipoObtenerTodos");
        }
    
        public virtual int cms_redesSocialesEmpresaActualizar(string url_facebook, string url_youtube)
        {
            var url_facebookParameter = url_facebook != null ?
                new ObjectParameter("url_facebook", url_facebook) :
                new ObjectParameter("url_facebook", typeof(string));
    
            var url_youtubeParameter = url_youtube != null ?
                new ObjectParameter("url_youtube", url_youtube) :
                new ObjectParameter("url_youtube", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_redesSocialesEmpresaActualizar", url_facebookParameter, url_youtubeParameter);
        }
    
        public virtual ObjectResult<cms_redesSocialesEmpresaObtener_Result> cms_redesSocialesEmpresaObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_redesSocialesEmpresaObtener_Result>("cms_redesSocialesEmpresaObtener");
        }
    
        public virtual int cms_seccionHomeNoticiasCarruselActualizar(Nullable<int> cms_seccion_home_carrusel_noticias_id, string url_redireccion, Nullable<int> orden, Nullable<bool> movil)
        {
            var cms_seccion_home_carrusel_noticias_idParameter = cms_seccion_home_carrusel_noticias_id.HasValue ?
                new ObjectParameter("cms_seccion_home_carrusel_noticias_id", cms_seccion_home_carrusel_noticias_id) :
                new ObjectParameter("cms_seccion_home_carrusel_noticias_id", typeof(int));
    
            var url_redireccionParameter = url_redireccion != null ?
                new ObjectParameter("url_redireccion", url_redireccion) :
                new ObjectParameter("url_redireccion", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            var movilParameter = movil.HasValue ?
                new ObjectParameter("movil", movil) :
                new ObjectParameter("movil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeNoticiasCarruselActualizar", cms_seccion_home_carrusel_noticias_idParameter, url_redireccionParameter, ordenParameter, movilParameter);
        }
    
        public virtual int cms_seccionHomeNoticiasCarruselDesactivar(Nullable<int> cms_seccion_home_carrusel_noticias_id)
        {
            var cms_seccion_home_carrusel_noticias_idParameter = cms_seccion_home_carrusel_noticias_id.HasValue ?
                new ObjectParameter("cms_seccion_home_carrusel_noticias_id", cms_seccion_home_carrusel_noticias_id) :
                new ObjectParameter("cms_seccion_home_carrusel_noticias_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeNoticiasCarruselDesactivar", cms_seccion_home_carrusel_noticias_idParameter);
        }
    
        public virtual int cms_seccionHomeNoticiasCarruselNuevo(string nombre_archivo, string url_redireccion, Nullable<int> orden, Nullable<bool> movil)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            var url_redireccionParameter = url_redireccion != null ?
                new ObjectParameter("url_redireccion", url_redireccion) :
                new ObjectParameter("url_redireccion", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            var movilParameter = movil.HasValue ?
                new ObjectParameter("movil", movil) :
                new ObjectParameter("movil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeNoticiasCarruselNuevo", nombre_archivoParameter, url_redireccionParameter, ordenParameter, movilParameter);
        }
    
        public virtual ObjectResult<cms_seccionHomeNoticiasCarruselObtener_Result> cms_seccionHomeNoticiasCarruselObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionHomeNoticiasCarruselObtener_Result>("cms_seccionHomeNoticiasCarruselObtener");
        }
    
        public virtual ObjectResult<Nullable<int>> cms_seccionHomeNoticiasCarruselObtenerUltimoOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("cms_seccionHomeNoticiasCarruselObtenerUltimoOrden");
        }
    
        public virtual int cms_seccionHomeSobreNosotrosActualizar(string contenido)
        {
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeSobreNosotrosActualizar", contenidoParameter);
        }
    
        public virtual int cms_seccionHomeSobreNosotrosActualizarNombreArchivo(string nombre_archivo)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeSobreNosotrosActualizarNombreArchivo", nombre_archivoParameter);
        }
    
        public virtual ObjectResult<cms_seccionHomeSobreNosotrosObtener_Result> cms_seccionHomeSobreNosotrosObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionHomeSobreNosotrosObtener_Result>("cms_seccionHomeSobreNosotrosObtener");
        }
    
        public virtual int cms_seccionHomeVideosEventosActualizar(Nullable<int> cms_seccion_home_videos_eventos_id, Nullable<int> orden)
        {
            var cms_seccion_home_videos_eventos_idParameter = cms_seccion_home_videos_eventos_id.HasValue ?
                new ObjectParameter("cms_seccion_home_videos_eventos_id", cms_seccion_home_videos_eventos_id) :
                new ObjectParameter("cms_seccion_home_videos_eventos_id", typeof(int));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeVideosEventosActualizar", cms_seccion_home_videos_eventos_idParameter, ordenParameter);
        }
    
        public virtual int cms_seccionHomeVideosEventosActualizarDescripcion(Nullable<int> cms_seccion_home_videos_eventos_id, string descripcion)
        {
            var cms_seccion_home_videos_eventos_idParameter = cms_seccion_home_videos_eventos_id.HasValue ?
                new ObjectParameter("cms_seccion_home_videos_eventos_id", cms_seccion_home_videos_eventos_id) :
                new ObjectParameter("cms_seccion_home_videos_eventos_id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeVideosEventosActualizarDescripcion", cms_seccion_home_videos_eventos_idParameter, descripcionParameter);
        }
    
        public virtual int cms_seccionHomeVideosEventosDesactivar(Nullable<int> cms_seccion_home_videos_eventos_id)
        {
            var cms_seccion_home_videos_eventos_idParameter = cms_seccion_home_videos_eventos_id.HasValue ?
                new ObjectParameter("cms_seccion_home_videos_eventos_id", cms_seccion_home_videos_eventos_id) :
                new ObjectParameter("cms_seccion_home_videos_eventos_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeVideosEventosDesactivar", cms_seccion_home_videos_eventos_idParameter);
        }
    
        public virtual int cms_seccionHomeVideosEventosNuevo(string nombre_archivo, Nullable<int> orden)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionHomeVideosEventosNuevo", nombre_archivoParameter, ordenParameter);
        }
    
        public virtual ObjectResult<cms_seccionHomeVideosEventosObtener_Result> cms_seccionHomeVideosEventosObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionHomeVideosEventosObtener_Result>("cms_seccionHomeVideosEventosObtener");
        }
    
        public virtual ObjectResult<string> cms_seccionHomeVideosEventosObtenerDescripcion(Nullable<int> cms_seccion_home_videos_eventos_id)
        {
            var cms_seccion_home_videos_eventos_idParameter = cms_seccion_home_videos_eventos_id.HasValue ?
                new ObjectParameter("cms_seccion_home_videos_eventos_id", cms_seccion_home_videos_eventos_id) :
                new ObjectParameter("cms_seccion_home_videos_eventos_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("cms_seccionHomeVideosEventosObtenerDescripcion", cms_seccion_home_videos_eventos_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> cms_seccionHomeVideosEventosObtenerUltimoOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("cms_seccionHomeVideosEventosObtenerUltimoOrden");
        }
    
        public virtual int cms_seccionNosotrosCarruselPlantasActualizarMovil(Nullable<int> id, Nullable<bool> movil)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var movilParameter = movil.HasValue ?
                new ObjectParameter("movil", movil) :
                new ObjectParameter("movil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosCarruselPlantasActualizarMovil", idParameter, movilParameter);
        }
    
        public virtual int cms_seccionNosotrosCarruselPlantasActualizarOrden(Nullable<int> id, Nullable<int> orden)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosCarruselPlantasActualizarOrden", idParameter, ordenParameter);
        }
    
        public virtual int cms_seccionNosotrosCarruselPlantasDesactivar(Nullable<int> cms_seccion_nosotros_carrusel_plantas_id)
        {
            var cms_seccion_nosotros_carrusel_plantas_idParameter = cms_seccion_nosotros_carrusel_plantas_id.HasValue ?
                new ObjectParameter("cms_seccion_nosotros_carrusel_plantas_id", cms_seccion_nosotros_carrusel_plantas_id) :
                new ObjectParameter("cms_seccion_nosotros_carrusel_plantas_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosCarruselPlantasDesactivar", cms_seccion_nosotros_carrusel_plantas_idParameter);
        }
    
        public virtual int cms_seccionNosotrosCarruselPlantasNuevo(string nombre_archivo, Nullable<int> orden, Nullable<bool> movil)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            var movilParameter = movil.HasValue ?
                new ObjectParameter("movil", movil) :
                new ObjectParameter("movil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosCarruselPlantasNuevo", nombre_archivoParameter, ordenParameter, movilParameter);
        }
    
        public virtual ObjectResult<cms_seccionNosotrosCarruselPlantasObtener_Result> cms_seccionNosotrosCarruselPlantasObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionNosotrosCarruselPlantasObtener_Result>("cms_seccionNosotrosCarruselPlantasObtener");
        }
    
        public virtual ObjectResult<Nullable<int>> cms_seccionNosotrosCarruselPlantasObtenerUltimoOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("cms_seccionNosotrosCarruselPlantasObtenerUltimoOrden");
        }
    
        public virtual int cms_seccionNosotrosLineaTiempoActualizar(string nombre_archivo)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosLineaTiempoActualizar", nombre_archivoParameter);
        }
    
        public virtual int cms_seccionNosotrosLineaTiempoNuevo(string nombre_archivo)
        {
            var nombre_archivoParameter = nombre_archivo != null ?
                new ObjectParameter("nombre_archivo", nombre_archivo) :
                new ObjectParameter("nombre_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionNosotrosLineaTiempoNuevo", nombre_archivoParameter);
        }
    
        public virtual ObjectResult<string> cms_seccionNosotrosLineaTiempoObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("cms_seccionNosotrosLineaTiempoObtener");
        }
    
        public virtual int cms_seccionProductosActualizarImagenTablaAplicacion(string imagenTablaAplicacion, Nullable<int> productoId)
        {
            var imagenTablaAplicacionParameter = imagenTablaAplicacion != null ?
                new ObjectParameter("imagenTablaAplicacion", imagenTablaAplicacion) :
                new ObjectParameter("imagenTablaAplicacion", typeof(string));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionProductosActualizarImagenTablaAplicacion", imagenTablaAplicacionParameter, productoIdParameter);
        }
    
        public virtual int cms_seccionProductosDocumentosActualizar(Nullable<int> id, string documento)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionProductosDocumentosActualizar", idParameter, documentoParameter);
        }
    
        public virtual ObjectResult<cms_seccionProductosDocumentosObtener_Result> cms_seccionProductosDocumentosObtener(Nullable<int> id_Producto)
        {
            var id_ProductoParameter = id_Producto.HasValue ?
                new ObjectParameter("id_Producto", id_Producto) :
                new ObjectParameter("id_Producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionProductosDocumentosObtener_Result>("cms_seccionProductosDocumentosObtener", id_ProductoParameter);
        }
    
        public virtual int cms_seccionProductosEliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionProductosEliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> cms_seccionProductosNuevo(Nullable<int> id_tipo, string sku, string nombre, string subnombre)
        {
            var id_tipoParameter = id_tipo.HasValue ?
                new ObjectParameter("id_tipo", id_tipo) :
                new ObjectParameter("id_tipo", typeof(int));
    
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var subnombreParameter = subnombre != null ?
                new ObjectParameter("subnombre", subnombre) :
                new ObjectParameter("subnombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("cms_seccionProductosNuevo", id_tipoParameter, skuParameter, nombreParameter, subnombreParameter);
        }
    
        public virtual int cms_seccionUsuariosEditar(Nullable<int> usuarioId, string pass)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_seccionUsuariosEditar", usuarioIdParameter, passParameter);
        }
    
        public virtual ObjectResult<cms_seccionUsuariosObtener_Result> cms_seccionUsuariosObtener(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_seccionUsuariosObtener_Result>("cms_seccionUsuariosObtener", usuarioIdParameter);
        }
    
        public virtual ObjectResult<cms_tablaAplicacionTituloObtener_Result> cms_tablaAplicacionTituloObtener(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_tablaAplicacionTituloObtener_Result>("cms_tablaAplicacionTituloObtener", id_productoParameter);
        }
    
        public virtual int cms_usuarioBorrar(Nullable<int> usuario_id)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cms_usuarioBorrar", usuario_idParameter);
        }
    
        public virtual ObjectResult<cms_websiteMensajeContactoObtener_Result> cms_websiteMensajeContactoObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cms_websiteMensajeContactoObtener_Result>("cms_websiteMensajeContactoObtener");
        }
    
        public virtual ObjectResult<fraseguModuloNivelObtenerPorModulo_Result> fraseguModuloNivelObtenerPorModulo(Nullable<int> frasegu_modulo_id)
        {
            var frasegu_modulo_idParameter = frasegu_modulo_id.HasValue ?
                new ObjectParameter("frasegu_modulo_id", frasegu_modulo_id) :
                new ObjectParameter("frasegu_modulo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fraseguModuloNivelObtenerPorModulo_Result>("fraseguModuloNivelObtenerPorModulo", frasegu_modulo_idParameter);
        }
    
        public virtual ObjectResult<fraseguModuloObtenerTodos_Result> fraseguModuloObtenerTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fraseguModuloObtenerTodos_Result>("fraseguModuloObtenerTodos");
        }
    
        public virtual int fraseguUsuarioPerfilEditar(Nullable<int> frasegu_usuario_perfil_id, string descripcion)
        {
            var frasegu_usuario_perfil_idParameter = frasegu_usuario_perfil_id.HasValue ?
                new ObjectParameter("frasegu_usuario_perfil_id", frasegu_usuario_perfil_id) :
                new ObjectParameter("frasegu_usuario_perfil_id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fraseguUsuarioPerfilEditar", frasegu_usuario_perfil_idParameter, descripcionParameter);
        }
    
        public virtual int fraseguUsuarioPerfilEliminar(Nullable<int> frasegu_usuario_perfil_id)
        {
            var frasegu_usuario_perfil_idParameter = frasegu_usuario_perfil_id.HasValue ?
                new ObjectParameter("frasegu_usuario_perfil_id", frasegu_usuario_perfil_id) :
                new ObjectParameter("frasegu_usuario_perfil_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fraseguUsuarioPerfilEliminar", frasegu_usuario_perfil_idParameter);
        }
    
        public virtual int fraseguUsuarioPerfilModuloNivelNuevo(Nullable<int> frasegu_usuario_perfil_id, Nullable<int> frasegu_modulo_nivel_id)
        {
            var frasegu_usuario_perfil_idParameter = frasegu_usuario_perfil_id.HasValue ?
                new ObjectParameter("frasegu_usuario_perfil_id", frasegu_usuario_perfil_id) :
                new ObjectParameter("frasegu_usuario_perfil_id", typeof(int));
    
            var frasegu_modulo_nivel_idParameter = frasegu_modulo_nivel_id.HasValue ?
                new ObjectParameter("frasegu_modulo_nivel_id", frasegu_modulo_nivel_id) :
                new ObjectParameter("frasegu_modulo_nivel_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fraseguUsuarioPerfilModuloNivelNuevo", frasegu_usuario_perfil_idParameter, frasegu_modulo_nivel_idParameter);
        }
    
        public virtual ObjectResult<fraseguUsuarioPerfilModuloNivelObtenerTodos_Result> fraseguUsuarioPerfilModuloNivelObtenerTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fraseguUsuarioPerfilModuloNivelObtenerTodos_Result>("fraseguUsuarioPerfilModuloNivelObtenerTodos");
        }
    
        public virtual int fraseguUsuarioPerfilNuevo(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fraseguUsuarioPerfilNuevo", descripcionParameter);
        }
    
        public virtual ObjectResult<fraseguUsuarioPerfilObtenerTodos_Result> fraseguUsuarioPerfilObtenerTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fraseguUsuarioPerfilObtenerTodos_Result>("fraseguUsuarioPerfilObtenerTodos");
        }
    
        public virtual int guardarMensajeContacto(string nombre, string email, string asunto, string mensaje)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("asunto", asunto) :
                new ObjectParameter("asunto", typeof(string));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("mensaje", mensaje) :
                new ObjectParameter("mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("guardarMensajeContacto", nombreParameter, emailParameter, asuntoParameter, mensajeParameter);
        }
    
        public virtual int ins_cms_seccion(Nullable<int> website_seccion_id, string titulo, string descripcion_corta)
        {
            var website_seccion_idParameter = website_seccion_id.HasValue ?
                new ObjectParameter("website_seccion_id", website_seccion_id) :
                new ObjectParameter("website_seccion_id", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var descripcion_cortaParameter = descripcion_corta != null ?
                new ObjectParameter("descripcion_corta", descripcion_corta) :
                new ObjectParameter("descripcion_corta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_cms_seccion", website_seccion_idParameter, tituloParameter, descripcion_cortaParameter);
        }
    
        public virtual int ins_cms_seccion_contenido(Nullable<int> cms_seccion_id, string html_control_id, string contenido)
        {
            var cms_seccion_idParameter = cms_seccion_id.HasValue ?
                new ObjectParameter("cms_seccion_id", cms_seccion_id) :
                new ObjectParameter("cms_seccion_id", typeof(int));
    
            var html_control_idParameter = html_control_id != null ?
                new ObjectParameter("html_control_id", html_control_id) :
                new ObjectParameter("html_control_id", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_cms_seccion_contenido", cms_seccion_idParameter, html_control_idParameter, contenidoParameter);
        }
    
        public virtual int ins_cms_website_menu(string url, string controlador, string accion, string texto, Nullable<int> cms_website_menu_padre_id)
        {
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var controladorParameter = controlador != null ?
                new ObjectParameter("controlador", controlador) :
                new ObjectParameter("controlador", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var textoParameter = texto != null ?
                new ObjectParameter("texto", texto) :
                new ObjectParameter("texto", typeof(string));
    
            var cms_website_menu_padre_idParameter = cms_website_menu_padre_id.HasValue ?
                new ObjectParameter("cms_website_menu_padre_id", cms_website_menu_padre_id) :
                new ObjectParameter("cms_website_menu_padre_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_cms_website_menu", urlParameter, controladorParameter, accionParameter, textoParameter, cms_website_menu_padre_idParameter);
        }
    
        public virtual int ins_producto(Nullable<int> var_id_tipo, string var_sku, string var_nombre, string var_descripcion, string var_presentacion, string var_contenido, string var_beneficios, string var_imagen, Nullable<double> var_precio, string var_pdf_nombre, string var_subnombre, string var_cintillo, Nullable<bool> var_show_index, string var_pie, string var_imagen_logo, string var_imagen_logo_carpeta, string var_imagen_logo_blanco)
        {
            var var_id_tipoParameter = var_id_tipo.HasValue ?
                new ObjectParameter("var_id_tipo", var_id_tipo) :
                new ObjectParameter("var_id_tipo", typeof(int));
    
            var var_skuParameter = var_sku != null ?
                new ObjectParameter("var_sku", var_sku) :
                new ObjectParameter("var_sku", typeof(string));
    
            var var_nombreParameter = var_nombre != null ?
                new ObjectParameter("var_nombre", var_nombre) :
                new ObjectParameter("var_nombre", typeof(string));
    
            var var_descripcionParameter = var_descripcion != null ?
                new ObjectParameter("var_descripcion", var_descripcion) :
                new ObjectParameter("var_descripcion", typeof(string));
    
            var var_presentacionParameter = var_presentacion != null ?
                new ObjectParameter("var_presentacion", var_presentacion) :
                new ObjectParameter("var_presentacion", typeof(string));
    
            var var_contenidoParameter = var_contenido != null ?
                new ObjectParameter("var_contenido", var_contenido) :
                new ObjectParameter("var_contenido", typeof(string));
    
            var var_beneficiosParameter = var_beneficios != null ?
                new ObjectParameter("var_beneficios", var_beneficios) :
                new ObjectParameter("var_beneficios", typeof(string));
    
            var var_imagenParameter = var_imagen != null ?
                new ObjectParameter("var_imagen", var_imagen) :
                new ObjectParameter("var_imagen", typeof(string));
    
            var var_precioParameter = var_precio.HasValue ?
                new ObjectParameter("var_precio", var_precio) :
                new ObjectParameter("var_precio", typeof(double));
    
            var var_pdf_nombreParameter = var_pdf_nombre != null ?
                new ObjectParameter("var_pdf_nombre", var_pdf_nombre) :
                new ObjectParameter("var_pdf_nombre", typeof(string));
    
            var var_subnombreParameter = var_subnombre != null ?
                new ObjectParameter("var_subnombre", var_subnombre) :
                new ObjectParameter("var_subnombre", typeof(string));
    
            var var_cintilloParameter = var_cintillo != null ?
                new ObjectParameter("var_cintillo", var_cintillo) :
                new ObjectParameter("var_cintillo", typeof(string));
    
            var var_show_indexParameter = var_show_index.HasValue ?
                new ObjectParameter("var_show_index", var_show_index) :
                new ObjectParameter("var_show_index", typeof(bool));
    
            var var_pieParameter = var_pie != null ?
                new ObjectParameter("var_pie", var_pie) :
                new ObjectParameter("var_pie", typeof(string));
    
            var var_imagen_logoParameter = var_imagen_logo != null ?
                new ObjectParameter("var_imagen_logo", var_imagen_logo) :
                new ObjectParameter("var_imagen_logo", typeof(string));
    
            var var_imagen_logo_carpetaParameter = var_imagen_logo_carpeta != null ?
                new ObjectParameter("var_imagen_logo_carpeta", var_imagen_logo_carpeta) :
                new ObjectParameter("var_imagen_logo_carpeta", typeof(string));
    
            var var_imagen_logo_blancoParameter = var_imagen_logo_blanco != null ?
                new ObjectParameter("var_imagen_logo_blanco", var_imagen_logo_blanco) :
                new ObjectParameter("var_imagen_logo_blanco", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_producto", var_id_tipoParameter, var_skuParameter, var_nombreParameter, var_descripcionParameter, var_presentacionParameter, var_contenidoParameter, var_beneficiosParameter, var_imagenParameter, var_precioParameter, var_pdf_nombreParameter, var_subnombreParameter, var_cintilloParameter, var_show_indexParameter, var_pieParameter, var_imagen_logoParameter, var_imagen_logo_carpetaParameter, var_imagen_logo_blancoParameter);
        }
    
        public virtual int ins_productos_aplicacion(Nullable<int> var_id_producto, string var_cultivo, string var_enfermedad, string var_dosis, string var_intervalo_seguridad, string var_observaciones, string var_epoca, string var_lmrp, string var_epa, string var_tolerancias, string var_estudios, Nullable<bool> var_agricultura_protegida)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            var var_cultivoParameter = var_cultivo != null ?
                new ObjectParameter("var_cultivo", var_cultivo) :
                new ObjectParameter("var_cultivo", typeof(string));
    
            var var_enfermedadParameter = var_enfermedad != null ?
                new ObjectParameter("var_enfermedad", var_enfermedad) :
                new ObjectParameter("var_enfermedad", typeof(string));
    
            var var_dosisParameter = var_dosis != null ?
                new ObjectParameter("var_dosis", var_dosis) :
                new ObjectParameter("var_dosis", typeof(string));
    
            var var_intervalo_seguridadParameter = var_intervalo_seguridad != null ?
                new ObjectParameter("var_intervalo_seguridad", var_intervalo_seguridad) :
                new ObjectParameter("var_intervalo_seguridad", typeof(string));
    
            var var_observacionesParameter = var_observaciones != null ?
                new ObjectParameter("var_observaciones", var_observaciones) :
                new ObjectParameter("var_observaciones", typeof(string));
    
            var var_epocaParameter = var_epoca != null ?
                new ObjectParameter("var_epoca", var_epoca) :
                new ObjectParameter("var_epoca", typeof(string));
    
            var var_lmrpParameter = var_lmrp != null ?
                new ObjectParameter("var_lmrp", var_lmrp) :
                new ObjectParameter("var_lmrp", typeof(string));
    
            var var_epaParameter = var_epa != null ?
                new ObjectParameter("var_epa", var_epa) :
                new ObjectParameter("var_epa", typeof(string));
    
            var var_toleranciasParameter = var_tolerancias != null ?
                new ObjectParameter("var_tolerancias", var_tolerancias) :
                new ObjectParameter("var_tolerancias", typeof(string));
    
            var var_estudiosParameter = var_estudios != null ?
                new ObjectParameter("var_estudios", var_estudios) :
                new ObjectParameter("var_estudios", typeof(string));
    
            var var_agricultura_protegidaParameter = var_agricultura_protegida.HasValue ?
                new ObjectParameter("var_agricultura_protegida", var_agricultura_protegida) :
                new ObjectParameter("var_agricultura_protegida", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_productos_aplicacion", var_id_productoParameter, var_cultivoParameter, var_enfermedadParameter, var_dosisParameter, var_intervalo_seguridadParameter, var_observacionesParameter, var_epocaParameter, var_lmrpParameter, var_epaParameter, var_toleranciasParameter, var_estudiosParameter, var_agricultura_protegidaParameter);
        }
    
        public virtual int ins_productos_composicion(Nullable<int> var_id_producto, string var_ingrediente, string var_formula, Nullable<bool> var_tipo, string var_porcentaje)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            var var_ingredienteParameter = var_ingrediente != null ?
                new ObjectParameter("var_ingrediente", var_ingrediente) :
                new ObjectParameter("var_ingrediente", typeof(string));
    
            var var_formulaParameter = var_formula != null ?
                new ObjectParameter("var_formula", var_formula) :
                new ObjectParameter("var_formula", typeof(string));
    
            var var_tipoParameter = var_tipo.HasValue ?
                new ObjectParameter("var_tipo", var_tipo) :
                new ObjectParameter("var_tipo", typeof(bool));
    
            var var_porcentajeParameter = var_porcentaje != null ?
                new ObjectParameter("var_porcentaje", var_porcentaje) :
                new ObjectParameter("var_porcentaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_productos_composicion", var_id_productoParameter, var_ingredienteParameter, var_formulaParameter, var_tipoParameter, var_porcentajeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ins_usuario(string nombre, string correo, string clave, Nullable<int> usuario_perfil_id, Nullable<int> usuario_mod)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var usuario_perfil_idParameter = usuario_perfil_id.HasValue ?
                new ObjectParameter("usuario_perfil_id", usuario_perfil_id) :
                new ObjectParameter("usuario_perfil_id", typeof(int));
    
            var usuario_modParameter = usuario_mod.HasValue ?
                new ObjectParameter("usuario_mod", usuario_mod) :
                new ObjectParameter("usuario_mod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ins_usuario", nombreParameter, correoParameter, claveParameter, usuario_perfil_idParameter, usuario_modParameter);
        }
    
        public virtual int ins_website_seccion(string titulo, string nombre_fichero_vista, string ruta_publica, string descripcion_corta, string descripcion)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var nombre_fichero_vistaParameter = nombre_fichero_vista != null ?
                new ObjectParameter("nombre_fichero_vista", nombre_fichero_vista) :
                new ObjectParameter("nombre_fichero_vista", typeof(string));
    
            var ruta_publicaParameter = ruta_publica != null ?
                new ObjectParameter("ruta_publica", ruta_publica) :
                new ObjectParameter("ruta_publica", typeof(string));
    
            var descripcion_cortaParameter = descripcion_corta != null ?
                new ObjectParameter("descripcion_corta", descripcion_corta) :
                new ObjectParameter("descripcion_corta", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_website_seccion", tituloParameter, nombre_fichero_vistaParameter, ruta_publicaParameter, descripcion_cortaParameter, descripcionParameter);
        }
    
        public virtual int modutrackNuevoIngresoAplicacion(Nullable<int> usuario_id, string sistema_ip, string sistema_operativo, string sistema_navegador)
        {
            var usuario_idParameter = usuario_id.HasValue ?
                new ObjectParameter("usuario_id", usuario_id) :
                new ObjectParameter("usuario_id", typeof(int));
    
            var sistema_ipParameter = sistema_ip != null ?
                new ObjectParameter("sistema_ip", sistema_ip) :
                new ObjectParameter("sistema_ip", typeof(string));
    
            var sistema_operativoParameter = sistema_operativo != null ?
                new ObjectParameter("sistema_operativo", sistema_operativo) :
                new ObjectParameter("sistema_operativo", typeof(string));
    
            var sistema_navegadorParameter = sistema_navegador != null ?
                new ObjectParameter("sistema_navegador", sistema_navegador) :
                new ObjectParameter("sistema_navegador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modutrackNuevoIngresoAplicacion", usuario_idParameter, sistema_ipParameter, sistema_operativoParameter, sistema_navegadorParameter);
        }
    
        public virtual int modutrackNuevoIngresoFallido(string correo_fallido, string pass_fallida, string sistema_ip, string sistema_operativo, string sistema_navegador)
        {
            var correo_fallidoParameter = correo_fallido != null ?
                new ObjectParameter("correo_fallido", correo_fallido) :
                new ObjectParameter("correo_fallido", typeof(string));
    
            var pass_fallidaParameter = pass_fallida != null ?
                new ObjectParameter("pass_fallida", pass_fallida) :
                new ObjectParameter("pass_fallida", typeof(string));
    
            var sistema_ipParameter = sistema_ip != null ?
                new ObjectParameter("sistema_ip", sistema_ip) :
                new ObjectParameter("sistema_ip", typeof(string));
    
            var sistema_operativoParameter = sistema_operativo != null ?
                new ObjectParameter("sistema_operativo", sistema_operativo) :
                new ObjectParameter("sistema_operativo", typeof(string));
    
            var sistema_navegadorParameter = sistema_navegador != null ?
                new ObjectParameter("sistema_navegador", sistema_navegador) :
                new ObjectParameter("sistema_navegador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modutrackNuevoIngresoFallido", correo_fallidoParameter, pass_fallidaParameter, sistema_ipParameter, sistema_operativoParameter, sistema_navegadorParameter);
        }
    
        public virtual int nuevoEventoAplicacion(string descripcion, Nullable<int> evento_aplicacion_tipo_id)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var evento_aplicacion_tipo_idParameter = evento_aplicacion_tipo_id.HasValue ?
                new ObjectParameter("evento_aplicacion_tipo_id", evento_aplicacion_tipo_id) :
                new ObjectParameter("evento_aplicacion_tipo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nuevoEventoAplicacion", descripcionParameter, evento_aplicacion_tipo_idParameter);
        }
    
        public virtual ObjectResult<search_productos_filtro_Result> search_productos_filtro(Nullable<int> var_id_cultivo, Nullable<int> var_id_enfermedad)
        {
            var var_id_cultivoParameter = var_id_cultivo.HasValue ?
                new ObjectParameter("var_id_cultivo", var_id_cultivo) :
                new ObjectParameter("var_id_cultivo", typeof(int));
    
            var var_id_enfermedadParameter = var_id_enfermedad.HasValue ?
                new ObjectParameter("var_id_enfermedad", var_id_enfermedad) :
                new ObjectParameter("var_id_enfermedad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_productos_filtro_Result>("search_productos_filtro", var_id_cultivoParameter, var_id_enfermedadParameter);
        }
    
        public virtual ObjectResult<sel_cms_seccion_contenido_Result> sel_cms_seccion_contenido(Nullable<int> website_seccion_id)
        {
            var website_seccion_idParameter = website_seccion_id.HasValue ?
                new ObjectParameter("website_seccion_id", website_seccion_id) :
                new ObjectParameter("website_seccion_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_cms_seccion_contenido_Result>("sel_cms_seccion_contenido", website_seccion_idParameter);
        }
    
        public virtual ObjectResult<sel_cms_website_menu_Result> sel_cms_website_menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_cms_website_menu_Result>("sel_cms_website_menu");
        }
    
        public virtual ObjectResult<sel_cultivos_para_filtros_Result> sel_cultivos_para_filtros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_cultivos_para_filtros_Result>("sel_cultivos_para_filtros");
        }
    
        public virtual ObjectResult<sel_enfermedades_para_filtro_por_cultivo_Result> sel_enfermedades_para_filtro_por_cultivo(Nullable<int> var_id_cultivo)
        {
            var var_id_cultivoParameter = var_id_cultivo.HasValue ?
                new ObjectParameter("var_id_cultivo", var_id_cultivo) :
                new ObjectParameter("var_id_cultivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_enfermedades_para_filtro_por_cultivo_Result>("sel_enfermedades_para_filtro_por_cultivo", var_id_cultivoParameter);
        }
    
        public virtual ObjectResult<sel_enfermedades_para_filtros_Result> sel_enfermedades_para_filtros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_enfermedades_para_filtros_Result>("sel_enfermedades_para_filtros");
        }
    
        public virtual ObjectResult<sel_producto_nombre_para_intra_ver_productos_Result> sel_producto_nombre_para_intra_ver_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_producto_nombre_para_intra_ver_productos_Result>("sel_producto_nombre_para_intra_ver_productos");
        }
    
        public virtual ObjectResult<sel_producto_tipo_Result> sel_producto_tipo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_producto_tipo_Result>("sel_producto_tipo");
        }
    
        public virtual ObjectResult<sel_productos_Result> sel_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_Result>("sel_productos");
        }
    
        public virtual ObjectResult<sel_productos_aplicacion_Fil_id_producto_Result> sel_productos_aplicacion_Fil_id_producto(Nullable<int> var_id_producto)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_aplicacion_Fil_id_producto_Result>("sel_productos_aplicacion_Fil_id_producto", var_id_productoParameter);
        }
    
        public virtual ObjectResult<sel_productos_composicion_Fil_id_producto_Result> sel_productos_composicion_Fil_id_producto(Nullable<int> var_id_producto)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_composicion_Fil_id_producto_Result>("sel_productos_composicion_Fil_id_producto", var_id_productoParameter);
        }
    
        public virtual ObjectResult<sel_productos_para_home_index_Result> sel_productos_para_home_index()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_home_index_Result>("sel_productos_para_home_index");
        }
    
        public virtual ObjectResult<sel_productos_para_intra_editar_productos_Result> sel_productos_para_intra_editar_productos(Nullable<int> var_producto_id)
        {
            var var_producto_idParameter = var_producto_id.HasValue ?
                new ObjectParameter("var_producto_id", var_producto_id) :
                new ObjectParameter("var_producto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_intra_editar_productos_Result>("sel_productos_para_intra_editar_productos", var_producto_idParameter);
        }
    
        public virtual ObjectResult<sel_productos_para_intra_ver_productos_Result> sel_productos_para_intra_ver_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_intra_ver_productos_Result>("sel_productos_para_intra_ver_productos");
        }
    
        public virtual ObjectResult<sel_productos_para_intra_ver_productos_filtro_Result> sel_productos_para_intra_ver_productos_filtro(Nullable<int> producto_tipo, string producto_sku, string producto_nombre)
        {
            var producto_tipoParameter = producto_tipo.HasValue ?
                new ObjectParameter("producto_tipo", producto_tipo) :
                new ObjectParameter("producto_tipo", typeof(int));
    
            var producto_skuParameter = producto_sku != null ?
                new ObjectParameter("producto_sku", producto_sku) :
                new ObjectParameter("producto_sku", typeof(string));
    
            var producto_nombreParameter = producto_nombre != null ?
                new ObjectParameter("producto_nombre", producto_nombre) :
                new ObjectParameter("producto_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_intra_ver_productos_filtro_Result>("sel_productos_para_intra_ver_productos_filtro", producto_tipoParameter, producto_skuParameter, producto_nombreParameter);
        }
    
        public virtual ObjectResult<sel_productos_para_producto_buscar_Result> sel_productos_para_producto_buscar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_producto_buscar_Result>("sel_productos_para_producto_buscar");
        }
    
        public virtual ObjectResult<sel_productos_para_proteccion_categoria_Result> sel_productos_para_proteccion_categoria(Nullable<int> var_id_tipo)
        {
            var var_id_tipoParameter = var_id_tipo.HasValue ?
                new ObjectParameter("var_id_tipo", var_id_tipo) :
                new ObjectParameter("var_id_tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_para_proteccion_categoria_Result>("sel_productos_para_proteccion_categoria", var_id_tipoParameter);
        }
    
        public virtual ObjectResult<sel_productos_sku_Result> sel_productos_sku()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_sku_Result>("sel_productos_sku");
        }
    
        public virtual ObjectResult<sel_productos_tipos_para_intra_ver_productos_Result> sel_productos_tipos_para_intra_ver_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_productos_tipos_para_intra_ver_productos_Result>("sel_productos_tipos_para_intra_ver_productos");
        }
    
        public virtual ObjectResult<sel_sku_para_intra_ver_productos_Result> sel_sku_para_intra_ver_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_sku_para_intra_ver_productos_Result>("sel_sku_para_intra_ver_productos");
        }
    
        public virtual ObjectResult<sel_tabla_aplicacion_titulo_por_id_producto_Result> sel_tabla_aplicacion_titulo_por_id_producto(Nullable<int> var_id_producto)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_tabla_aplicacion_titulo_por_id_producto_Result>("sel_tabla_aplicacion_titulo_por_id_producto", var_id_productoParameter);
        }
    
        public virtual ObjectResult<sel_tabla_composicion_por_id_producto_Result> sel_tabla_composicion_por_id_producto(Nullable<int> var_id_producto)
        {
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_tabla_composicion_por_id_producto_Result>("sel_tabla_composicion_por_id_producto", var_id_productoParameter);
        }
    
        public virtual ObjectResult<sp_temp_buscador_v1_Result> sp_temp_buscador_v1(string var_cultivo, string var_enfermedad)
        {
            var var_cultivoParameter = var_cultivo != null ?
                new ObjectParameter("var_cultivo", var_cultivo) :
                new ObjectParameter("var_cultivo", typeof(string));
    
            var var_enfermedadParameter = var_enfermedad != null ?
                new ObjectParameter("var_enfermedad", var_enfermedad) :
                new ObjectParameter("var_enfermedad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_temp_buscador_v1_Result>("sp_temp_buscador_v1", var_cultivoParameter, var_enfermedadParameter);
        }
    
        public virtual int upd_producto(Nullable<int> var_id_tipo, string var_sku, string var_nombre, string var_subnombre, string var_descripcion, string var_presentacion, string var_contenido, string var_beneficios, string var_cintillo, string var_pie, Nullable<int> var_producto_id)
        {
            var var_id_tipoParameter = var_id_tipo.HasValue ?
                new ObjectParameter("var_id_tipo", var_id_tipo) :
                new ObjectParameter("var_id_tipo", typeof(int));
    
            var var_skuParameter = var_sku != null ?
                new ObjectParameter("var_sku", var_sku) :
                new ObjectParameter("var_sku", typeof(string));
    
            var var_nombreParameter = var_nombre != null ?
                new ObjectParameter("var_nombre", var_nombre) :
                new ObjectParameter("var_nombre", typeof(string));
    
            var var_subnombreParameter = var_subnombre != null ?
                new ObjectParameter("var_subnombre", var_subnombre) :
                new ObjectParameter("var_subnombre", typeof(string));
    
            var var_descripcionParameter = var_descripcion != null ?
                new ObjectParameter("var_descripcion", var_descripcion) :
                new ObjectParameter("var_descripcion", typeof(string));
    
            var var_presentacionParameter = var_presentacion != null ?
                new ObjectParameter("var_presentacion", var_presentacion) :
                new ObjectParameter("var_presentacion", typeof(string));
    
            var var_contenidoParameter = var_contenido != null ?
                new ObjectParameter("var_contenido", var_contenido) :
                new ObjectParameter("var_contenido", typeof(string));
    
            var var_beneficiosParameter = var_beneficios != null ?
                new ObjectParameter("var_beneficios", var_beneficios) :
                new ObjectParameter("var_beneficios", typeof(string));
    
            var var_cintilloParameter = var_cintillo != null ?
                new ObjectParameter("var_cintillo", var_cintillo) :
                new ObjectParameter("var_cintillo", typeof(string));
    
            var var_pieParameter = var_pie != null ?
                new ObjectParameter("var_pie", var_pie) :
                new ObjectParameter("var_pie", typeof(string));
    
            var var_producto_idParameter = var_producto_id.HasValue ?
                new ObjectParameter("var_producto_id", var_producto_id) :
                new ObjectParameter("var_producto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_producto", var_id_tipoParameter, var_skuParameter, var_nombreParameter, var_subnombreParameter, var_descripcionParameter, var_presentacionParameter, var_contenidoParameter, var_beneficiosParameter, var_cintilloParameter, var_pieParameter, var_producto_idParameter);
        }
    
        public virtual int upd_productos_aplicacion(Nullable<int> var_id, string var_cultivo, string var_enfermedad, string var_dosis, string var_intervalo_seguridad, string var_observaciones, string var_epoca, string var_lmrp, string var_epa, string var_tolerancias, string var_estudios, Nullable<bool> var_agricultura_protegida)
        {
            var var_idParameter = var_id.HasValue ?
                new ObjectParameter("var_id", var_id) :
                new ObjectParameter("var_id", typeof(int));
    
            var var_cultivoParameter = var_cultivo != null ?
                new ObjectParameter("var_cultivo", var_cultivo) :
                new ObjectParameter("var_cultivo", typeof(string));
    
            var var_enfermedadParameter = var_enfermedad != null ?
                new ObjectParameter("var_enfermedad", var_enfermedad) :
                new ObjectParameter("var_enfermedad", typeof(string));
    
            var var_dosisParameter = var_dosis != null ?
                new ObjectParameter("var_dosis", var_dosis) :
                new ObjectParameter("var_dosis", typeof(string));
    
            var var_intervalo_seguridadParameter = var_intervalo_seguridad != null ?
                new ObjectParameter("var_intervalo_seguridad", var_intervalo_seguridad) :
                new ObjectParameter("var_intervalo_seguridad", typeof(string));
    
            var var_observacionesParameter = var_observaciones != null ?
                new ObjectParameter("var_observaciones", var_observaciones) :
                new ObjectParameter("var_observaciones", typeof(string));
    
            var var_epocaParameter = var_epoca != null ?
                new ObjectParameter("var_epoca", var_epoca) :
                new ObjectParameter("var_epoca", typeof(string));
    
            var var_lmrpParameter = var_lmrp != null ?
                new ObjectParameter("var_lmrp", var_lmrp) :
                new ObjectParameter("var_lmrp", typeof(string));
    
            var var_epaParameter = var_epa != null ?
                new ObjectParameter("var_epa", var_epa) :
                new ObjectParameter("var_epa", typeof(string));
    
            var var_toleranciasParameter = var_tolerancias != null ?
                new ObjectParameter("var_tolerancias", var_tolerancias) :
                new ObjectParameter("var_tolerancias", typeof(string));
    
            var var_estudiosParameter = var_estudios != null ?
                new ObjectParameter("var_estudios", var_estudios) :
                new ObjectParameter("var_estudios", typeof(string));
    
            var var_agricultura_protegidaParameter = var_agricultura_protegida.HasValue ?
                new ObjectParameter("var_agricultura_protegida", var_agricultura_protegida) :
                new ObjectParameter("var_agricultura_protegida", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_aplicacion", var_idParameter, var_cultivoParameter, var_enfermedadParameter, var_dosisParameter, var_intervalo_seguridadParameter, var_observacionesParameter, var_epocaParameter, var_lmrpParameter, var_epaParameter, var_toleranciasParameter, var_estudiosParameter, var_agricultura_protegidaParameter);
        }
    
        public virtual int upd_productos_aplicacion_inactive(Nullable<int> var_id)
        {
            var var_idParameter = var_id.HasValue ?
                new ObjectParameter("var_id", var_id) :
                new ObjectParameter("var_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_aplicacion_inactive", var_idParameter);
        }
    
        public virtual int upd_productos_composicion(string var_ingrediente, string var_formula, string var_porcentaje, Nullable<int> var_id)
        {
            var var_ingredienteParameter = var_ingrediente != null ?
                new ObjectParameter("var_ingrediente", var_ingrediente) :
                new ObjectParameter("var_ingrediente", typeof(string));
    
            var var_formulaParameter = var_formula != null ?
                new ObjectParameter("var_formula", var_formula) :
                new ObjectParameter("var_formula", typeof(string));
    
            var var_porcentajeParameter = var_porcentaje != null ?
                new ObjectParameter("var_porcentaje", var_porcentaje) :
                new ObjectParameter("var_porcentaje", typeof(string));
    
            var var_idParameter = var_id.HasValue ?
                new ObjectParameter("var_id", var_id) :
                new ObjectParameter("var_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_composicion", var_ingredienteParameter, var_formulaParameter, var_porcentajeParameter, var_idParameter);
        }
    
        public virtual int upd_productos_composicion_inactive(Nullable<int> var_id)
        {
            var var_idParameter = var_id.HasValue ?
                new ObjectParameter("var_id", var_id) :
                new ObjectParameter("var_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_composicion_inactive", var_idParameter);
        }
    
        public virtual int upd_productos_imagen_color(string var_logo_color, Nullable<int> var_producto_id)
        {
            var var_logo_colorParameter = var_logo_color != null ?
                new ObjectParameter("var_logo_color", var_logo_color) :
                new ObjectParameter("var_logo_color", typeof(string));
    
            var var_producto_idParameter = var_producto_id.HasValue ?
                new ObjectParameter("var_producto_id", var_producto_id) :
                new ObjectParameter("var_producto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_imagen_color", var_logo_colorParameter, var_producto_idParameter);
        }
    
        public virtual int upd_productos_imagen_logo_blanco(string var_imagen_logo_blanco, Nullable<int> var_producto_id)
        {
            var var_imagen_logo_blancoParameter = var_imagen_logo_blanco != null ?
                new ObjectParameter("var_imagen_logo_blanco", var_imagen_logo_blanco) :
                new ObjectParameter("var_imagen_logo_blanco", typeof(string));
    
            var var_producto_idParameter = var_producto_id.HasValue ?
                new ObjectParameter("var_producto_id", var_producto_id) :
                new ObjectParameter("var_producto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_imagen_logo_blanco", var_imagen_logo_blancoParameter, var_producto_idParameter);
        }
    
        public virtual int upd_productos_imagen_render(string var_render, Nullable<int> var_producto_id)
        {
            var var_renderParameter = var_render != null ?
                new ObjectParameter("var_render", var_render) :
                new ObjectParameter("var_render", typeof(string));
    
            var var_producto_idParameter = var_producto_id.HasValue ?
                new ObjectParameter("var_producto_id", var_producto_id) :
                new ObjectParameter("var_producto_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_productos_imagen_render", var_renderParameter, var_producto_idParameter);
        }
    
        public virtual int upd_titulo_tabla_aplicacion(Nullable<int> var_id_columna, string var_titulo, Nullable<int> var_id_producto)
        {
            var var_id_columnaParameter = var_id_columna.HasValue ?
                new ObjectParameter("var_id_columna", var_id_columna) :
                new ObjectParameter("var_id_columna", typeof(int));
    
            var var_tituloParameter = var_titulo != null ?
                new ObjectParameter("var_titulo", var_titulo) :
                new ObjectParameter("var_titulo", typeof(string));
    
            var var_id_productoParameter = var_id_producto.HasValue ?
                new ObjectParameter("var_id_producto", var_id_producto) :
                new ObjectParameter("var_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_titulo_tabla_aplicacion", var_id_columnaParameter, var_tituloParameter, var_id_productoParameter);
        }
    
        public virtual int usuarioNuevo(string nombre, string correo, string clave, Nullable<int> usuario_perfil_id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var usuario_perfil_idParameter = usuario_perfil_id.HasValue ?
                new ObjectParameter("usuario_perfil_id", usuario_perfil_id) :
                new ObjectParameter("usuario_perfil_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usuarioNuevo", nombreParameter, correoParameter, claveParameter, usuario_perfil_idParameter);
        }
    
        public virtual ObjectResult<usuarioObtTodos_Result> usuarioObtTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usuarioObtTodos_Result>("usuarioObtTodos");
        }
    
        public virtual ObjectResult<Nullable<int>> val_login(string correo, string clave, string ip_usuario)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var ip_usuarioParameter = ip_usuario != null ?
                new ObjectParameter("ip_usuario", ip_usuario) :
                new ObjectParameter("ip_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("val_login", correoParameter, claveParameter, ip_usuarioParameter);
        }
    
        public virtual ObjectResult<website_sp1_Result> website_sp1(Nullable<int> productoId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<website_sp1_Result>("website_sp1", productoIdParameter);
        }
    
        public virtual ObjectResult<website_sp2_Result> website_sp2(Nullable<int> productoId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<website_sp2_Result>("website_sp2", productoIdParameter);
        }
    
        public virtual ObjectResult<website_sp3_Result> website_sp3(Nullable<int> productoId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<website_sp3_Result>("website_sp3", productoIdParameter);
        }
    
        public virtual ObjectResult<website_sp4_Result> website_sp4(Nullable<int> productoId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<website_sp4_Result>("website_sp4", productoIdParameter);
        }
    
        public virtual ObjectResult<website_sp5_Result> website_sp5(Nullable<int> productoId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<website_sp5_Result>("website_sp5", productoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> website_sp6(Nullable<int> p_id_producto)
        {
            var p_id_productoParameter = p_id_producto.HasValue ?
                new ObjectParameter("p_id_producto", p_id_producto) :
                new ObjectParameter("p_id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("website_sp6", p_id_productoParameter);
        }
    }
}
